[package]
name = "crates-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.16"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
